# Generated by Django 4.1.7 on 2023-04-12 18:09

from django.db import migrations
from django.db.migrations import RunPython


def func(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'fixture_data.json')


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0003_alter_dish_price"),
    ]

    operations = [RunPython(func, reverse_func)]
